version: '3'
services:
  wwww:
    image: php:8.0-apache
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html/"
    ports:
      - 80:80
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=kdpeq8_rtt
      - MYSQL_USER=kdpeq8
      - MYSQL_PASSWORD=kdpeq8
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306